README.md
interview_guide_engineer.md
slack_rules.md

- @mayuminnieee からの依頼で、カジュアル面談申し込みフォームを追加しました
- @mayuminnieee がApproveしたら
- いくつかのファイルにリンクが散らばっているといつかリンクを消したり変更したりする時に漏れそうではあるんですが、まあいったん直で書いていいかと思っています
- 更新頻度次第ではあるのでまた問題になりそうだったら考えましょう

Add casual meeting form

---

README.md

ref: #25 
We're hiring badgeを追加しました

Add hiring badge

---

articles.md

ref: none
- 色々アップデートがあったので記事一覧を更新しました
- 意外とアウトプット多くてビックリした
- リンクの見栄えが悪かったのでフォーマットを少し修正しました

Modify articles

---

articles.md

ref: none
CodeZineに寄稿した記事（SREチームの取り組み）へのリンクを追加しました
レビューが通ればOK

関連記事まとめにCodeZineのリンクを追加

---

.github/dependabot.yml

このPull Requestで対応したことを簡潔に書いてください。
どういう状態になればマージできるかを書いてください。

dependabotを設定した

---

articles.md

このPull Requestで対応したことを簡潔に書いてください。
どういう状態になればマージできるかを書いてください。

ブログを公開したので一覧に追加した

---

articles.md
interview_guide_engineer.md

close #55
#55 に全部書いてある
レビュー通ったら
特になし。応募者からのフィードバックありがたいですね

Add Android/iOS casual meeting blog link

---

articles.md

ref: https://github.com/Kyash/recruitment/issues/46
近況報告を書きました！

書いたblogを追加

---

articles.md

ref: https://github.com/Kyash/recruitment/issues/47
書きました！！！
チーム文化をウリにって感じなので社内の取り組みにカテゴライズしました。

Visa Proxyの話を寄稿

---

articles.md

ref: #56 
pf-protoの記事を投稿したので追加しときました！

pf-protoの記事を追加

---

articles.md

ref: #54
追加した！
CIが通ったら
リリーストレインの話も入っているのでプロダクト開発のセクションに入れました

『他チームにも知っておいてもらいたいAndroid/iOSのリリース知識』を追加

---

articles.md

このPull Requestで対応したことを簡潔に書いてください。
どういう状態になればマージできるかを書いてください。

Add blog entry

---

articles.md

ref: #{https://github.com/Kyash/recruitment/issues/60}
2021/07/30 追加記事 `SREメンバーの半数が地方勤務な話` のリンクを追加します
追記内容及びURLが問題なければMergeできます
特になし

SREメンバーの半数が地方勤務な話 を追加します

---

articles.md

ref: #85 
Title says everything.
CIが通ったら
特にナシ

『Kyash QAチームの改善の取り組みについて』を記事一覧に追加

---

articles.md

ref: #83 
Title says everything.
CIが通ったら
特にナシ

記事一覧に『特定のSlackチャネルに全メンバーを一括招待するコマンドをZapierで作る』を追加

---

articles.md

add: new article ゼロから始める、データ分析と可視化

---

articles.md

ref: https://github.com/Kyash/recruitment/issues/90
article.mdに記事を追加しました
リンクとタイトルが正しいこと

Kyashではじめて育休を取得した話を追加した

---

articles.md

ref: #96 
追加しました！
CIが通ったら
特にナシ

「KyashのAPIのテストにおけるPostmanの運用方針」を追加

---

articles.md

ref: #99 
倉林の1.5年経過後のブログを追加しました。
すぐにマージ大丈夫です。

Prince第二ブログを追加しました。

---

articles.md

Kyashの採用リポジトリを公開して1年の振り返りを追加

---

articles.md

ref: #89
公開したブログ記事のリンクを追加した
リンクが正しく設定されておりレビューが通ればOK

Terraformのブログ記事を追加した

---

articles.md

ref: #92 
タイトルの通り
リンクが正しく設定されておりレビューが通ればOK！

カテゴリ機能のアニメーションを実装したブログ記事追加

---

articles.md

ref: #106
Datadog Profilerを導入したBlogへのリンクを追加しました
リンクが正しく設定されておりレビューが通れば

Add link for dd profiler blog

---

articles.md

OPSチームの記事を追加

---

articles.md

『iOSDC 2021 LTで話した『Kyash iOSアプリのQAの歴史』のスライド補足』を追加

---

articles.md

Jetpack Compose から始める、アクセシビリティ の記事追加

---

interview_guide_engineer.md

オファー面談のプロセスが変更になったので修正しました
- before
- CEO / 30分
- after
- CTO / 45分
@mayuminnieee にレビューもらったら

オファー面談の内容を修正

---

interview_guide_engineer.md

ref: https://github.com/Kyash/recruitment/pull/127/files#r771052133
2次面接の内容を修正しました
@mayuminnieee にOKをもらったら

2次面接のフローを修正

---

articles.md

Kyashブログを書いたので追加
どういう状態になればマージできるかを書いてください。

add new blog

---

interview_guide_engineer.md

change-serverside-flow-doc

---

articles.md

前回更新時点より増えた記事を追加しました。
誰かがApproveしてくれたら
特になし

Kyash関連記事の最新化

---

README.md
interview_guide_engineer.md
mobile_basic_knowledge.md
slack_rules.md

採用のtalentioリンクをherpに置き換えました
approved

replace talentio link to herp link
